### PR TITLE
Cross-Platform (Clojure + ClojureScript) Support

### PR DESCRIPTION
**Pull request by sdedovic**
- refactor for cross-platform support
- add example code
- update readme with new sections

#1 #2

### CODE REVIEW

**Comment by sdedovic** [comment]
CC: @verberktstan

Please take a look at the PR. I _think_ this will do what you want but I don't use ClojureScript so I would greatly appreciate:
1. some testing if you can
2. guidelines on how to publish the code. Will Clojars suffice or is there an NPM equivalent (or just NPM) for Clojurescript libraries?
3. Any further thoughts?

**Comment by verberktstan** [comment]
Yeah, looks great, love the approach! Nicely extracted the math utilities to work crossplatform. :+1: 

I'm currently trying to get this working with the cljsbuild leiningen plugin. If i manage to make it work i'll propose something for tests and publishing!

**Comment by verberktstan** [comment]
I've got the tests working (simple node tests with shadow-cljs).
I'll open a fork!

**Comment by verberktstan** [comment]
See #4 for node tests via shadow-cljs.
I think it's fine for now to publish a new release via Clojars. If anyone would want to use this lib in cljs, they probably use lein, shadow-cljs or deps.edn. In all cases they can use Clojars deps for cljs (as well as clj).

**Comment by sdedovic** [comment]
Hey I'm traveling at the moment - will try to get this all merged in this week.

**Comment by sdedovic** [comment]
Fun fact - I'm on a Mac M3 and some tests fail. Running `OpenJDK 64-Bit Server VM Temurin-21.0.1+12` I think the values in the tests are hardware-dependent.

Replaced the `==` operator with `(< (abs (- a b)) 1e-6))` and it all passes now!

**Pull request merged**
